from datetime import date, datetime
from decimal import Decimal
from sqlalchemy import BigInteger, Date, DateTime, ForeignKey, Numeric, String, Text
from sqlalchemy.orm import Mapped, mapped_column
from app.models.base import Base

class Quotation(Base):
    __tablename__ = "quotations"
    id: Mapped[int] = mapped_column(BigInteger, primary_key=True)
    quotation_number: Mapped[str] = mapped_column(String(100), unique=True, nullable=False)
    rfq_id: Mapped[int] = mapped_column(BigInteger, ForeignKey("rfqs.id", ondelete="RESTRICT"), nullable=False)
    case_id: Mapped[int] = mapped_column(BigInteger, ForeignKey("cases.id", ondelete="RESTRICT"), nullable=False)
    customer_id: Mapped[int] = mapped_column(BigInteger, ForeignKey("customers.id", ondelete="RESTRICT"), nullable=False)
    contact_id: Mapped[int | None] = mapped_column(BigInteger, ForeignKey("customer_contacts.id", ondelete="SET NULL"))
    quotation_date: Mapped[date] = mapped_column(Date, nullable=False)
    valid_until: Mapped[date | None] = mapped_column(Date)
    currency: Mapped[str | None] = mapped_column(String(10))
    incoterm: Mapped[str | None] = mapped_column(String(20))
    delivery_location: Mapped[str | None] = mapped_column(String(255))
    payment_terms: Mapped[str | None] = mapped_column(Text)
    delivery_time: Mapped[str | None] = mapped_column(String(255))
    warranty: Mapped[str | None] = mapped_column(String(255))
    origin: Mapped[str | None] = mapped_column(String(255))
    price_basis: Mapped[str | None] = mapped_column(String(50))
    subtotal: Mapped[Decimal] = mapped_column(Numeric(20,6), default=0)
    discount: Mapped[Decimal] = mapped_column(Numeric(20,6), default=0)
    additional_cost: Mapped[Decimal] = mapped_column(Numeric(20,6), default=0)
    grand_total: Mapped[Decimal] = mapped_column(Numeric(20,6), default=0)
    status: Mapped[str] = mapped_column(String(40), default="DRAFT", nullable=False)
    source_template: Mapped[str | None] = mapped_column(String(500))
    customer_notes: Mapped[str | None] = mapped_column(Text)
    internal_notes: Mapped[str | None] = mapped_column(Text)
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True))
    updated_at: Mapped[datetime] = mapped_column(DateTime(timezone=True))

class QuotationLine(Base):
    __tablename__ = "quotation_lines"
    id: Mapped[int] = mapped_column(BigInteger, primary_key=True)
    quotation_id: Mapped[int] = mapped_column(BigInteger, ForeignKey("quotations.id", ondelete="CASCADE"), nullable=False)
    rfq_line_id: Mapped[int] = mapped_column(BigInteger, ForeignKey("rfq_lines.id", ondelete="RESTRICT"), nullable=False)
    line_number: Mapped[int] = mapped_column(nullable=False)
    description: Mapped[str | None] = mapped_column(Text)
    part_id: Mapped[int | None] = mapped_column(BigInteger, ForeignKey("parts.id", ondelete="SET NULL"))
    manufacturer: Mapped[str | None] = mapped_column(String(255))
    part_number: Mapped[str | None] = mapped_column(String(255))
    brand: Mapped[str | None] = mapped_column(String(255))
    quantity: Mapped[Decimal | None] = mapped_column(Numeric(18,4))
    unit: Mapped[str | None] = mapped_column(String(50))
    condition: Mapped[str | None] = mapped_column(String(50))
    supplier_quote_line_id: Mapped[int | None] = mapped_column(BigInteger, ForeignKey("supplier_quote_lines.id", ondelete="SET NULL"))
    pricing_calculation_id: Mapped[int | None] = mapped_column(BigInteger, ForeignKey("pricing_calculations.id", ondelete="SET NULL"))
    target_purchase_price: Mapped[Decimal | None] = mapped_column(Numeric(20,6))
    actual_purchase_price: Mapped[Decimal | None] = mapped_column(Numeric(20,6))
    purchase_currency: Mapped[str | None] = mapped_column(String(10))
    exchange_rate: Mapped[Decimal | None] = mapped_column(Numeric(20,8))
    exchange_rate_date: Mapped[date | None] = mapped_column(Date)
    freight_cost: Mapped[Decimal] = mapped_column(Numeric(20,6), default=0)
    insurance_cost: Mapped[Decimal] = mapped_column(Numeric(20,6), default=0)
    customs_cost: Mapped[Decimal] = mapped_column(Numeric(20,6), default=0)
    clearance_cost: Mapped[Decimal] = mapped_column(Numeric(20,6), default=0)
    local_delivery_cost: Mapped[Decimal] = mapped_column(Numeric(20,6), default=0)
    financial_cost: Mapped[Decimal] = mapped_column(Numeric(20,6), default=0)
    other_cost: Mapped[Decimal] = mapped_column(Numeric(20,6), default=0)
    landed_cost: Mapped[Decimal | None] = mapped_column(Numeric(20,6))
    margin_type: Mapped[str | None] = mapped_column(String(30))
    margin_value: Mapped[Decimal | None] = mapped_column(Numeric(12,6))
    calculated_selling_price: Mapped[Decimal | None] = mapped_column(Numeric(20,6))
    manual_selling_price: Mapped[Decimal | None] = mapped_column(Numeric(20,6))
    final_selling_price: Mapped[Decimal | None] = mapped_column(Numeric(20,6))
    selling_total_price: Mapped[Decimal | None] = mapped_column(Numeric(20,6))
    currency: Mapped[str | None] = mapped_column(String(10))
    delivery_time: Mapped[str | None] = mapped_column(String(255))
    origin: Mapped[str | None] = mapped_column(String(255))
    warranty: Mapped[str | None] = mapped_column(String(255))
    technical_compliance: Mapped[str | None] = mapped_column(String(40))
    deviation: Mapped[str | None] = mapped_column(Text)
    verification_status: Mapped[str | None] = mapped_column(String(40))
    pricing_status: Mapped[str | None] = mapped_column(String(40))
    override_reason: Mapped[str | None] = mapped_column(Text)
    notes: Mapped[str | None] = mapped_column(Text)
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True))
    updated_at: Mapped[datetime] = mapped_column(DateTime(timezone=True))
